create user springaopex identified by springaopex;
grant connect, resource to springaopex;

CREATE TABLE SPRINGAOPEX(
	SID NUMBER PRIMARY KEY,
	SPASS VARCHAR2(200)
);

CREATE TABLE LOG(
	LID NUMBER PRIMARY KEY,
	LSID NUMBER,
	LSPASS_BEFORE VARCHAR2(200),
	LSPASS_AFTER VARCHAR2(200),
	LSORT VARCHAR2(20), -- "INSERT" 또는 "UPDATE" 또는 "DELETE"
	LREGDATE TIMESTAMP
);

CREATE SEQUENCE SEQ_SPRINGAOPEX;
CREATE SEQUENCE SEQ_LOG;

SELECT * FROM SPRINGAOPEX;
SELECT * FROM LOG;