[CMD]
sqlplus conn as sysdba

[SQLPLUS]
SQL> create user jdbcboard identified by jdbcboard;
SQL> grant connect, resource to jdbcboard;
SQL> conn jdbcboard/jdbcboard;

CREATE SEQUENCE BOARD_SEQ;
CREATE SEQUENCE ARTICLE_SEQ;
CREATE SEQUENCE REPLY_SEQ;

CREATE TABLE BOARD (
BID NUMBER PRIMARY KEY,
BNAME NVARCHAR2(100) NOT NULL,
BACNT NUMBER
);

CREATE TABLE MEMBER (
MID VARCHAR2(20) PRIMARY KEY,
MNAME NVARCHAR2(100) NOT NULL,
MALIAS NVARCHAR2(100),
MPASS VARCHAR2(200) NOT NULL,
MEMAIL VARCHAR2(200),
MCP VARCHAR2(20),
MDELYN CHAR(1)
);

CREATE TABLE ARTICLE (
AID NUMBER PRIMARY KEY,
ASUBJECT NVARCHAR2(200) NOT NULL,
ACONTENT NVARCHAR2(2000),
AVCNT NUMBER,
AREGDATE TIMESTAMP,
ADELYN CHAR(1),
AAFCNT NUMBER,
ARCNT NUMBER,
BID NUMBER,
MID VARCHAR2(20),
FOREIGN KEY (BID) REFERENCES BOARD(BID),
FOREIGN KEY (MID) REFERENCES MEMBER(MID) 
);

CREATE TABLE REPLY (
RID NUMBER PRIMARY KEY,
RCONTENT NVARCHAR2(2000),
RREGDATE TIMESTAMP,
RDELYN CHAR(1),
MID VARCHAR2(20),
AID NUMBER,
FOREIGN KEY (MID) REFERENCES MEMBER(MID),
FOREIGN KEY (AID) REFERENCES ARTICLE(AID) 
);

CREATE OR REPLACE TRIGGER TRG_UPDATE_BACNT
AFTER INSERT ON ARTICLE
FOR EACH ROW
BEGIN
	UPDATE BOARD SET BACNT = BACNT + 1 WHERE BID=:NEW.BID; 
END;


