CREATE SEQUENCE BOARD_SEQ;
CREATE SEQUENCE ARTICLE_SEQ;
CREATE SEQUENCE REPLY_SEQ;
CREATE SEQUENCE SEQ_QUERYLOG;

CREATE TABLE BOARD(
	BID NUMBER PRIMARY KEY,
	BNAME NVARCHAR2(100) NOT NULL,
	BACNT NUMBER
);

CREATE TABLE MEMBER(
	MID VARCHAR2(20) PRIMARY KEY,
	MNAME NVARCHAR2(100) NOT NULL,
	MALIAS NVARCHAR2(100),
	MPASS VARCHAR2(200) NOT NULL,
	MEMAIL VARCHAR2(200),
	MCP VARCHAR2(20),
	MDELYN CHAR(1)
);

CREATE TABLE ARTICLE(
	AID NUMBER PRIMARY KEY,
	ASUBJECT NVARCHAR2(200) NOT NULL,
	ACONTENT NVARCHAR2(2000),
	AVCNT NUMBER,
	AREGDATE TIMESTAMP,
	ADELYN CHAR(1),
	AAFCNT NUMBER,
	ARCNT NUMBER,
	BID NUMBER,
	MID VARCHAR2(20),
	FOREIGN KEY(BID) REFERENCES BOARD(BID),
	FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);

CREATE TABLE REPLY(
	RID NUMBER PRIMARY KEY,
	RCONTENT NVARCHAR2(2000),
	RREGDATE TIMESTAMP,
	RDELYN CHAR(1),
	MID VARCHAR2(20),
	AID NUMBER,
	FOREIGN KEY(MID) REFERENCES MEMBER(MID),
	FOREIGN KEY(AID) REFERENCES ARTICLE(AID)
);

CREATE TABLE QUERYLOG(
	QID NUMBER PRIMARY KEY,
	TNAME VARCHAR2(20),
	QSORT VARCHAR2(20),
	MID VARCHAR(20),
	QREGDATE TIMESTAMP,
	FOREIGN KEY(MID) REFERENCES MEMBER(MID)
);

CREATE TABLE ATTACHFILE(
	AFID NUMBER PRIMARY KEY,
	AFCNAME NVARCHAR2(200) NOT NULL,
	AFSNAME NVARCHAR2(200) NOT NULL,
	AFREGDATE TIMESTAMP,
	AID NUMBER, 
	FOREIGN KEY(AID) REFERENCES ARTICLE(AID)
);
CREATE SEQUENCE SEQ_ATTACHFILE;

CREATE OR REPLACE TRIGGER TRG_UPDATE_BACNT
AFTER INSERT ON ARTICLE
FOR EACH ROW
BEGIN
	UPDATE BOARD SET BACNT = BACNT + 1 WHERE BID=:NEW.BID;
END;

CREATE OR REPLACE TRIGGER TRG_UPDATE_ARCNT
AFTER INSERT ON REPLY
FOR EACH ROW
BEGIN
	UPDATE ARTICLE SET ARCNT = ARCNT + 1 WHERE AID=:NEW.AID;
END;

CREATE OR REPLACE TRIGGER TRG_DELETE_ARCNT
AFTER UPDATE ON REPLY
FOR EACH ROW
BEGIN
	UPDATE ARTICLE SET ARCNT = ARCNT - 1 WHERE AID=:NEW.AID;
END;

CREATE OR REPLACE TRIGGER TRG_INCREASE_AAFCNT
AFTER INSERT ON ATTACHFILE
FOR EACH ROW
BEGIN 
	UPDATE ARTICLE SET AAFCNT = AAFCNT + 1 WHERE AID=:NEW.AID;
END;

CREATE OR REPLACE TRIGGER TRG_DECREASE_AAFCNT
AFTER DELETE ON ATTACHFILE
FOR EACH ROW
BEGIN 
	UPDATE ARTICLE SET AAFCNT = AAFCNT - 1 WHERE AID=:OLD.AID;
END;

SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM ARTICLE ORDER BY AID DESC;
SELECT * FROM REPLY;
SELECT * FROM QUERYLOG;
SELECT * FROM ATTACHFILE;

SELECT * 
FROM (
	SELECT ROWNUM AS RNUM, A.* 
	FROM(
		SELECT * FROM ARTICLE ORDER BY AID DESC
	) A
	WHERE ROWNUM <= 19 
)
WHERE RNUM > 10;

SELECT * FROM 
	(SELECT ROWNUM AS RNUM, ALLATC.*
	FROM 
		(SELECT 
			A.AID AID, A.ASUBJECT ASUBJECT, A.ACONTENT ACONTENT, A.AVCNT AVCNT, 
			A.AREGDATE AREGDATE, A.ADELYN ADELYN, A.AAFCNT AAFCNT, A.ARCNT ARCNT, 
			A.BID BID, A.MID MID, B.BNAME BNAME 
		FROM 
			ARTICLE A, BOARD B
		WHERE 
			A.BID = B.BID 
			AND 
			A.ADELYN='N'
		ORDER BY AID DESC
	) ALLATC
	WHERE ROWNUM <= 10
)
WHERE RNUM > 0;


